### ISSUE TITLE
💡 [Feature]: Add forms for scaffolding and other create flows instead of QA approach

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#124]
## 🎯 Aim of the feature

Currently when scaffold a new project or run the CI/CD action the user needs to go over answering a couple of steps before the action runs. This is a bit misleading as the user has no info how many more steps there are, it's also hard to get an overview of what was set in previous steps etc. 
Instead of the current approach a better one would be to create dedicated full page views which would present all the steps and inputs the user needs to fill in order to proceed with the flow. Some options might be optional. Also this provides an opportunity to extend the forms with our own custom made steps.

What should we refactor:
- [x] CI/CD GitHub workflow action
- [x] Scaffolding of a new SPFx project
    - [x] Additional here we could add custom steps that should be done after the project is created. User could provide it's own custom steps or pick one of the predifined once like installing pnp.js or fast-serve.
