### ISSUE TITLE
💡 [Feature]: Add more managing SPFx extensions functionality

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#15]
## 🎯 Aim

The aim would be to extend the environment view of the extension to provide more functionalities which will allow to management of webparts and extension in all app catalogs on user tenant

![image](https://github.com/pnp/vscode-viva/assets/58668583/8562e947-b85d-45ad-ba89-e886ff72e62f)

Some of the activities could allow:
- [x] move the sharepoint main page link to the account view and rename it to tenant
    - [x] show link to SharePoint admin page
    - [x] show link to webApiPermissionManagement
- [x] present solutions deployed per app catalog #215
- [x] add tenant-wide view to see tenant-wide deployed application customizers
- [ ] show and 'attach' form customizers to a specific content type

## 🤔 Other 

Some reference commands:
https://pnp.github.io/cli-microsoft365/cmd/spo/applicationcustomizer/applicationcustomizer-add/
https://pnp.github.io/cli-microsoft365/cmd/spo/tenant/tenant-applicationcustomizer-add/
https://pnp.github.io/cli-microsoft365/cmd/spo/contenttype/contenttype-set/ (modify content type to set the form customizer on a specific form)
https://pnp.github.io/cli-microsoft365/cmd/spo/customaction/customaction-add/

**Comment by Adam-it** [comment]
lets start dividing this to smaller issues

**Comment by Adam-it** [comment]
I think we may close this up and for the `show and 'attach' form customizers to a specific content type` create a dedicated issue
