### ISSUE TITLE
💡 [Feature]: Extend the scaffolding custom steps feature

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#185]
## 🎯 Aim of the feature

A follow up based on feature #124.
The aim would be to:

- [ ] add a step which will configure fast serve #218
- [ ] add possitiblity to add custom steps #217
- [ ] based on project type add a custom step to install react (for example for application customizer) #216

**Comment by Adam-it** [comment]
I should include link with reference to the packages

**Comment by Adam-it** [comment]
I should add the basic setup for PNP/sp

**Comment by Adam-it** [comment]
since we have separate smaller issues open lets close this up
