### ISSUE TITLE
💡 [Feature]: Enhance App management actions

### ISSUE THREAD

**Issue by Saurabh7019** [pnp/vscode-viva#324]
### 🎯 Aim of the feature

This is a follow up to issue #215 and proposes additional actions for managing apps within the tenant and site collection app catalogs. The aim is to extend the existing capabilities to manage apps by including the following features:

- [x] Allow the promotion of apps from site collection app catalogs to the tenant app catalog.
- [x] Install the app to a specified site collection (introduce an additional input field to specify the site URL where an app should be installed).
- [x] Uninstall the app from a specified site collection (introduce an additional input field to specify the site URL from which an app should be uninstalled).
- [x] Upgrade the app at a specified site collection.
- [x] Allow copying solutions between app catalogs (from site level to tenant level and vice versa).
- [x] Allow moving solutions between app catalogs (from site level to tenant level and vice versa).

### 📷 Images (if possible) with expected result

![image](https://github.com/user-attachments/assets/ac564009-ad99-46ee-a48e-266da1ae9de7)

### 🤔 Additional remarks or comments

Parent issue #215

**Comment by Adam-it** [comment]
@Saurabh7019 I rechecked and the above suggestions for additional actions are fine and TBH I don't have many other ideas. 
I have only one obesrvattion that we should prompt for confirmation. For example currently if we click on the remove we should show yes/no prompt to confirm the action before removing. The same we should add for the uninstall.

I suggest we open app separate issues for the following functionalities which we mentioned in this issue and when we will have all issues ready and speced let's close this one:
Lets add:
- [ ] an issue to add the confirmation on remove
- [ ] an issue which will allow to copy or/and move app from one app catalog to another (this will also cover the promote state to move from site level to tenant level app catalog
- [ ] an issue that will allow to install or/and uninstall an app from a specifiet site collection
- [ ] an issue that will allow to upgrade app at specified site collection

@Saurabh7019 what do you think of the above and the way I grouped them into 4 issues. Let me know what you think so that I will create them one by one in the repo and we may start opening them up for implementation 🚀

**Comment by Saurabh7019** [comment]
Not providing confirmation on the "Remove" action was a big mistake. I really hope this hasn't caused issues for anyone.

The grouping you have proposed looks perfect. It's both easier to implement and simpler to merge. Please go ahead and create the issues. I will pick them up for implementation as soon as they are ready.

**Comment by Adam-it** [comment]
> Not providing confirmation on the "Remove" action was a big mistake. I really hope this hasn't caused issues for anyone.

I wouldn't worry about that so much. I didn't get any negative feed related to this and it is rather new functionality that not everybody know about or use it. That's why we also need to work a looot on promoting 😅

**Comment by Adam-it** [comment]
> The grouping you have proposed looks perfect. It's both easier to implement and simpler to merge. Please go ahead and create the issues. I will pick them up for implementation as soon as they are ready.

Ok I added 3 new issues as a good start. I still need to create last one with the copy/move actions but before I do that I need to think on that a bit 🤔

**Comment by Adam-it** [comment]
I speced out issues for the last features. Lets close it up and focus on the separate issues
