### ISSUE TITLE
Epic: Product Marketing

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#35]
## 🎯 Aim of the feature

The aim is to list out all actions that might help in the product:
- [x] release a 1.0 version of the product. This will create confidence in the product. In order to do that I am waiting for a green light (I guess @VesaJuvonen this one is on you 😉)
- [x] prepare short HOWTO movies presenting tool features
- [x] add more documentation about the product to make it easier to use and promote it https://github.com/pnp/vscode-viva/issues/50
- [X] add a blog post going over the tool features -> https://github.com/pnp/blog/pull/1348
- [x] #73

**Comment by Adam-it** [comment]
viva connections toolkit movies 
https://www.youtube.com/watch?v=jXQFgGlId00&list=PLR9nK3mnD-OW1XNbtsHiFDG___W8wnfHp&index=4
