### ISSUE TITLE
📣 Promote SPFx Toolkit 

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#355]
A lot of awesome stuff was done and brought to the product. We may always do better and improve and add more and more features but if we won't promote and tell anyone then it just does not make sense. 
The aim is to help others in their SPFx development so we need to spread the word to make it easy to find and checkout this extension.

In this issue I want to gather ideas/suggestions of couple of promoting activities we may do and then create separate issues for them so they could be even taken by contributors of this repository. 
I am open for any suggestion so if you are reading this issue feel free to just leave comment 👍🙏.

Some ideas:
- Social media engagement
    - [x] LinkedIn tips post campaign and regular release updates - this we already do. TBH we don't have a lot of engagement in our tip posts, so maybe we could somehow work on them a bit
    - [x] BlueSky tips post campaign and regular release updates  - TBH I am not sure we have an official PnP account already. Need to recheck this with Vesa and how we could get access to it
    - [X] ~~X ??? - TBH I would drop this but maybe 🤔~~ - dropping this idea

- Blog posts on PnP blog
    - [x] #363 
    - [x] #364
    - [ ] #365
    - [x] #366
    - [x] #367
    
- Video tutorials - in the past when this still was Viva Connections Toolkit I did some shorts about this tool and it got some engagement. It was our intro in shorts in our YT and it was a total pain to do 😅. But maybe it's worth recheking
    - [x] ..... thinking/working on it - we have a YT playlist on the PnP Channel https://www.youtube.com/watch?v=NyH7ATaEKRI&list=PLR9nK3mnD-OVKlm8lyeFuuHmiouR-u40a
    
- Community call demos
    - [x] #368
    - [x] #369
    - [x] #370

- [X] ~~Promo video about SPFx Toolkit - I was thinking of a short (3 min) short movie that would just showcase some functionalities of the product and would just do a general brief overlook of the tool~~ - dropping this idea

- [x] #352 - having a webpage which is indexed, searchable will also help and it may also be a place to store common use cases/ examples of SPFx Toolkit features 

Previous marketing things done are all grouped in this [wiki page](https://github.com/pnp/vscode-viva/wiki/2.-Marketing-resources)

**Comment by nicodecleyre** [comment]
Great idea! A bluesky account can be a next step, linked to every merge 😉

**Comment by Adam-it** [comment]
> Great idea! A bluesky account can be a next step, linked to every merge 😉 

TBH we did that in CLI for M365 that we have dedicated channels/accounts for CLI. 
I am not sure it is the best approach, as then we need to work on followers and engagement which is a lot of effort and time which currently I don't have. 
This is a good idea but currently I would stick with using official PnP accounts and channels and post updates and messages using them

**Comment by nicodecleyre** [comment]
Totally fine.

Can these official PnP Accounts be used to spreak tips like "did you know that with the SPFx toolkit, you can validate your project"? 🤔 

next to that: 

- [ ] blogposts
- [ ] video tutorials
- [ ] community call demo's

**Comment by Adam-it** [comment]
> Can these official PnP Accounts be used to spreak tips like "did you know that with the SPFx toolkit, you can validate your project"? 🤔

Yes totally, this is what we already do in LinkedIn where we use the official PnP account to post many tip updates. Also regarding CLI for M365 and also about SPFx Toolkit. The biggest advantage is that we don't need to work on gaining followers as we already have a lot of them that just follow PnP community. So this is what we want to do. 
As of now I have only access/right to LinkedIn account but I want to already do the same with bluesky as soon as it will be ready. 

> next to that:
> 
> * [ ]  blogposts
> * [ ]  video tutorials
> * [ ]  community call demo's

Those are very good ideas, keep those coming 👏👏👏! I will add those to the initial post of this issue and let's start gathering ideas on blog post topic or what we could show in each tutorial etc.

**Comment by nicodecleyre** [comment]
> @nicodecleyre I updated the initial post based on your suggestions. I think those are very good areas 👍. Now lets work on the details 😉

Really cool! Very clear now that you have split it up by domain 🤩
Here are some ideas that pop up in my head:
- Social media engagement
i would also drop X as it seems that the Microsoft Community is moved to Bsky
- [ ] **Success stories:** how the SPFx toolkit can tackle (or 'could', based on real-life cases 🤔 ) use cases
- [ ] **did you know?:** giving a feature a spotlight. Like "did you know you can validate..."
- [ ] **interactivity:** if we could somehow do an interactive questioning with the audience and respond how SPFx Toolkit can solve/help with those problems
- [ ] **the journey**: how it started, how SPFx evolved into todays toolkit

- Blog ideas
- [ ] Getting started with SPFx Toolkit
- [ ] x features (hidden gems 😜 ) that will save you hours
- [ ] x best practices that will save you hours
- [ ] SPFx toolkit vs alternative (or vs manually 😄 )
- [ ] a case study (how SPFx toolkit helped to tackle a real life scenario)
- [ ] how to upgrade your SPFx solution (which can be a real pita if you have to do it manually)
- [ ] how to use the chat functionality to manage your tenant
- [ ] how to manage your tenant wide extensions with SPFx toolkit

  
- Video tutorials 
- [ ] same as blog ideas
- [ ] deploy like a pro
- [ ] use together with Teams toolkit
- [ ] frequent pitfalls in SPFx toolkit and how the toolkit can tackle them

- Community call demos
- [ ] Introduction/how to get started
- [ ] any feature higlight (with deep dive of this feature)
- [ ] How to contribute
- [ ] comparisons with manual work and how the toolkit can save you hours

**Comment by Adam-it** [comment]
@nicodecleyre those are some awesome ideas 👏🤩

as for Social media engagement I like all of the suggestions 👍. I will try to create a separate issue and start working on the content so we may schedule those kind of posts from December for next 2 months

as for Blog ideas:
- 'x best practices that will save you hours' - this may be a touchy subject 🤔. As there is no such thing as 'best' practice. There are good once and usually those are connected to coding style and preference. But there are some good practices that for example our spfx snippets help keep🤔
- 'how to use the chat functionality to manage your tenant' - this is still early beta and has many glitches.. but for a future idea why not👍
- 'how to manage your tenant wide extensions with SPFx toolkit' - I would rather go with apps in general. What @Saurabh7019 added with the manage actions and what we have in this issue #324 is a goldmine 🤩

as for Video tutorials and for Community call demos those are good ideas. Not yet specific but I may work on it and create some initial list based on the functionalities we have

Thanks @nicodecleyre for engaging in this brainstorm. This is a great help 👏👏👏. You Rock 🤩

Based on our discussion I will try to create some initial list ASAP and let you know what you think about it. And then lets just create issue per item (blog post, video, community call demo) so that we may try to engage others to help out 😍

**Comment by Saurabh7019** [comment]
> * **did you know?:** giving a feature a spotlight. Like "did you know you can validate..."

There are so many great ideas here and this one is my favorite. I think weekly feature spotlights could do wonders to promote this tool. Also, if community leaders in the SharePoint space could mention it on LinkedIn/BlueSky, it could encourage more developers to check it out.

**Comment by Adam-it** [comment]
@Saurabh7019, @nicodecleyre I spec'ed out a couple of issues for creating blog posts and doing a demo on one of the PnP community calls.

**Comment by Adam-it** [comment]
As soon as the last item for this epic issue gets closed, let's close this one as well and do not continue spending time on this but instead focus on the promoting items we discussed internally

**Comment by Adam-it** [comment]
✅
